# Generated by Django 4.2.4 on 2023-09-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users_table',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'trainer_table',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(default='')),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField(default='')),
                ('trainerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trainer')),
            ],
            options={
                'db_table': 'workoutplan_table',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(default='')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('workoutId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.workoutplan')),
            ],
            options={
                'db_table': 'exercise_table',
            },
        ),
    ]
