# Generated by Django 4.2.4 on 2023-09-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='trainer',
            new_name='trainerId',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='goal',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(default='')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('workoutId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.workoutplan')),
            ],
        ),
    ]
