# Generated by Django 4.2.4 on 2023-09-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_nutritionplan_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(default='')),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField(default='')),
                ('completed', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customuser')),
            ],
            options={
                'db_table': 'goal_table',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('completed', models.TextField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customuser')),
            ],
            options={
                'db_table': 'activity_table',
            },
        ),
    ]
